---
title: "Placing Archival Maps"
subtitle: "Assignment 3"
description: "How can we place archival maps in their social, historical, and cartographic context?"
sidebar: links
---

| Assigned      | Due           |
|---------------|---------------|
| March 9, 2026 | April 3, 2026 |

# Assignment overview

This group assignment asks you to create an “exhibit” or product that situates the map(s) your group is focusing on within their historical and geographic context. Rather than accept these maps as honest and straightforward representations of the world, the exhibit/product you create should highlight how they were created by people in particular positions to achieve a historically and geographically specific set of goals. This is not to say you need to pass judgment on these goals–being critical does not always mean taking an antagonistic position. Rather, your group should help us understand how the map(s) you are focusing on reflect choices about what or who should be mapped, whose interests should be prioritized, and how to best represent the world cartographically.

## Let's make that more concrete!

I’m suggesting two main types of products for your group to consider.

1.  **A virtual exhibit using the ArcGIS Storymap platform**. With this approach, you would include map(s) from your main object along with 6-8 other items from special collections. That would be structured in the following way:

    1.  A couple of paragraphs providing an **introduction** to your exhibit. This can include a description of the map(s) that are the main focus, the central theme you want to emphasize about those maps, and anything else that a viewer should keep in mind in looking through the artifacts you’ve collected.

    2.  **A** **photo/image, citation, and caption** for your main map(s) and each artifact in your exhibit. The photo can be from your phone, or you can use a digitized version if available. The citation should be in APA format–[here’s one guide](https://libguides.csudh.edu/archives-citation/apa) to using that for archival materials. We will discuss captions in class, but they should be relatively short (no more than a paragraph) and provide notable details/features that viewers should pay attention to and an explanation of how this artifact fits within the broader exhibit. [Here’s one chapter](https://drive.google.com/file/d/1QzaDQND_rpnHx2N8SHJnkhxC4VwiNM2T/view?usp=sharing) on writing good captions.

    3.  Lastly, you should have a final section of a few paragraphs that situates the exhibit you’ve created within **the context of our class**. What are the connections to our readings thus far in the course? How does this exhibit help sharpen our thinking about the role of maps in urban spaces and urban life? Think of it as an explanation of how your exhibit fits within the museum (our class). 

2.  **A visual mosaic of map(s) from your main item along with other relevant archival materials.** With this approach, think of the conversation we had with Meghan Kelly and the work of Margaret Pearce on maps like “[They Would Not Take Me There](https://storymaps.arcgis.com/stories/2b5792be16d64f9e999ec93cd436bc17)”. Or you could think of work [to reinterpret historical monuments such as confederate statues](https://hyperallergic.com/remagining-monuments-to-make-them-resonate-locally-and-personally/)here in the Southeast. The goal for those cartographers is using visuals and text to situate maps, to understand the positionalities of mappers and those being mapped. The goal is to show how the map itself is not an objective mirror of reality but a historically and culturally specific visual object. It’s to call attention to aspects of these maps we might otherwise take for granted. More concretely, you can either digitally or physically alter your map while also adding archival materials or other text/visuals to help contextualize it. Here, too, you should think about a story you want to tell about your map–how it shows the world in ways that reflect its intended purpose, time, and place. Your group can consider what this might look like. I’ve got funds to print things out if you want.\
    \
    If you choose option 2, I’d also ask your group to provide an ***interpretative guide*** of no more than 2 single spaced pages that provides an introduction to your visual (what’s its title?, what’s the main focus?) as well as walking us through your design. It should also cite any items your group used (see information on how to do that in choice 1 above)

# Assignment criteria

For either option, I will be assessing your group’s project based on the following criteria:

-   Your project should demonstrate your ability to use archival research techniques to locate and interpret materials in UGA’s Special Collections library.

-   Your project should draw upon techniques, approaches, and concepts discussed in our class to this point.

-   Your project should provide insights into the cultural, political, and historical context for your map(s)

-   Your project should draw clear and thoughtful connections between the archival materials you include.

I’ll be rating all of these criteria on the same scale as other assignments (Definitely/good enough/not yet/not addressed), and your group will have a chance to revise if the assignment is rated incomplete. 

# Submission details

This document can be submitted on ELC under Assignments. This can be a link to your group's storymap or a digital image file along with your interpretive guide,

# Project options

-   [Moving Ahead With Macon](https://galileo-uga.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma9910300523902959&context=L&vid=01GALI_UGA:UGA&lang=en&search_scope=MyInstitution&adaptor=Local%20Search%20Engine&tab=LibraryCatalog&query=any,contains,moving%20ahead%20with%20macon%20&sortby=rank&facet=library,include,2959%E2%80%93530589490002959){target="_blank"}

    -   [Scanned map 1](https://github.com/jshannon75/geog4636_mapsandthecity/blob/main/items/MovingAheadWithMacon_map1.pdf){target="_blank"}

    -   [Scanned map 2](https://github.com/jshannon75/geog4636_mapsandthecity/blob/main/items/MovingAheadWithMacon_map2.pdf){target="_blank"}

-   [Techwood neighborhood: Social base map survey of Atlanta, GA](https://dlg.usg.edu/record/gsu_planatl_22866?canvas=22&x=555&y=755&w=2927){target="_blank"}; [Full text](https://github.com/jshannon75/geog4636_mapsandthecity/blob/main/items/Social base map survey of Atlanta.pdf){target="_blank"}

-   [Metropolitan North Georgia Water Planning District records: Nutrient Loading in the Lower Chattahoochee](https://sclfind.libs.uga.edu/catalog/ms4069_aspace_ref83_bqh){target="_blank"}

-   [Rodney Mims Cook papers on Urban Renewal in University Center: Box 10](https://sclfind.libs.uga.edu/catalog/RBRL180RMC_aspace_ref209_no2){target="_blank"}

-   [Georgia Wildlife Federation: Alcovy River Greenway project](https://sclfind.libs.uga.edu/catalog/ms3995_aspace_ref325_i9w){target="_blank"}

-   [Athens R-51 Urban Renewal Project](https://dlg.usg.edu/record/guan_1633_014c-001?canvas=0&x=400&y=400&w=1986){target="_blank"}

-   [Union, South Carolina: James Hunt plans for low rent housing](https://sclfind.libs.uga.edu/catalog/ms2901_aspace_ref2200_y3m){target="_blank"}; [Selected pages](https://github.com/jshannon75/geog4636_mapsandthecity/blob/main/items/Hunt_UnionSC.pdf){target="_blank"}

# Related materials

-   [Worksheet for your group's main map](https://docs.google.com/document/d/1oPL7h7p4AVN1daiFkwa1_UwIBTkGLM594ANQHotE4KQ/edit?usp=sharing){target="_blank"}

-   [Worksheet for other materials you look at](https://docs.google.com/document/d/1y9C6Vo1rnN-LwVgK9tRfgOOznPehjeBudMgUo6P1nCo/edit?usp=sharing){target="_blank"}